// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD7pEV6WC_faQb1c6_Mpvl2fAXYXrCLUE',
    appId: '1:197409820696:web:9d3ecc86f717fb5526f36d',
    messagingSenderId: '197409820696',
    projectId: 'flufire-demo-project',
    authDomain: 'flufire-demo-project.firebaseapp.com',
    storageBucket: 'flufire-demo-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLONDGNW1VFNvxgmiUPO1pS5DleaQ6KkM',
    appId: '1:197409820696:android:55623b142f5d2c6426f36d',
    messagingSenderId: '197409820696',
    projectId: 'flufire-demo-project',
    storageBucket: 'flufire-demo-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO--ZtObY3dnDMuT5wQVcfRFZ6cw7giEY',
    appId: '1:197409820696:ios:d9a724aba251d4a326f36d',
    messagingSenderId: '197409820696',
    projectId: 'flufire-demo-project',
    storageBucket: 'flufire-demo-project.appspot.com',
    iosClientId:
        '197409820696-2qdqmf2g7ud487vi26gk8tud42g8ti8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO--ZtObY3dnDMuT5wQVcfRFZ6cw7giEY',
    appId: '1:197409820696:ios:d9a724aba251d4a326f36d',
    messagingSenderId: '197409820696',
    projectId: 'flufire-demo-project',
    storageBucket: 'flufire-demo-project.appspot.com',
    iosClientId:
        '197409820696-2qdqmf2g7ud487vi26gk8tud42g8ti8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemo',
  );
}
